- name: Create config direcory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ app_root_path }}"
    - "{{ config_path }}"

- name: Render 3proxy config
  template: 
    src: "3proxy.cfg"
    dest: "{{ config_path }}/3proxy.cfg"

- name: Copy docker related files
  template:
    src: "{{ item }}"
    dest: "{{ app_root_path }}"
  with_items:
    - Dockerfile
    - docker-compose.yml

- name: Build image from Dockerfile
  docker_image:
    build:
      path: "{{ app_root_path }}"
    name: 3proxy
    tag: "{{ app_version }}"
    source: build
    
- name: Copy 3proxy systemcd service
  template:
    src: 3proxy.service
    dest: /etc/systemd/system/

- name: Enable and start 3proxy service
  service:
    name: 3proxy
    enabled: yes
    state: started

