- name: Create config direcory
  file: path={{ item }} state=directory
  with_items:
    /root/3proxy-role
    /opt/3proxy

- name: Copy 3proxy config
  template: src="3proxy.cfg.j2" dest="/opt/3proxy/3proxy.cfg"

- name: Copy Dockerfile
  copy: src="Dockerfile" dest="/root/3proxy-role"

- name: Create docker-compose.yml from template
  template: src="docker-compose.yml.j2" dest="/root/3proxy-role"

- name: Copy 3proxy systemcd service
  copy: scr="3proxy.service" dest="/usr/lib/systemd/system"

- name: Start 3proxy service
  systemd: state=started name=3proxy

- name: Enable 3proxy service
  systemd: enabled=yes name=3proxy 
