- name: Create config direcory
  file: dest={{ item }} state=directory
  with_items:
    - /root/3proxy-role
    - /opt/3proxy

- name: Copy 3proxy config
  template: src="3proxy.cfg.j2" dest="/opt/3proxy/3proxy.cfg"

- name: Copy docker related files
  copy: src={{ item }} dest="/root/3proxy-role"
  with_items:
    - Dockerfile
    - docker-compose.yml

- name: Build image from Dockerfile
  command: docker build -t 3proxy:latest /root/3proxy-role
    
- name: Copy 3proxy systemcd service
  copy: src="3proxy.service" dest="/usr/lib/systemd/system"

- name: Enable and start 3proxy service
  service:
    name: 3proxy
    enabled: yes
    state: started

