version: '3'
services:
  socks5:
    container_name: "3proxy"
    image: "3proxy:{{ app_version }}"
    ports:
      - "10138:8080"
      - "20138:3128"
    volumes:
      - "{{ config_path }}/3proxy.cfg:/etc/3proxy/3proxy.cfg"
      - "{{ config_path }}/3proxy.log:/var/log/3proxy.log"
